apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: backend
    repoURL: 'https://github.com/ppaciekq/ArgoCD.git'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
